name: Create 
on:
  workflow_dispatch:
jobs:
  provision:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
    - name: Create Resource Group
      uses: sn-cscharf/GitHubAction.CreateResourceGroup@master
      with:
        name: TEST-GROUP-DEV
        location: westeurope
    - name: Create Service Plan
      uses: sn-cscharf/GitHubAction.CreateAppServicePlan@main
