name: Create Resource Group GitHub Action Example TEST
on:
  workflow_dispatch:
jobs:
  provision:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
    - name: Remove Resource Group
      uses: sn-cscharf/GitHubAction.RemoveResourceGroup@master
      with:
        name: Some-Name
        
