on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
      - name: Hello world action step
        id: hello
        uses: sn-cscharf/GitHubAction.JavaTest@main
        with:
          name: 'TEST-GROUP-DEV2'
          location: 'westeurope'
      # Use the output from the `hello` step
      - name: Get the output time
        run: | 
          echo "The time was ${{ steps.hello.outputs.group }}"
          echo "The time was ${{ steps.hello.outputs.group.id }}"
          echo "The time was ${{ steps.hello.outputs.group.name }}"
          echo "The time was ${{ steps.hello.outputs.group.properties.provisioningState }}"
