name: Create Resource Group GitHub Action Example TEST
on:
  push:
    branches:
      - main
jobs:
  provision:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
    - name: Create Resource Group
      id: step_one
      uses: sn-cscharf/GitHubAction.CreateResourceGroup@master
      with:
        name: ${{ github.ref_name }}
        location: westeurope
    - name: Echo Outputs
      run: |
        echo "The id is ${{ steps.step_one.outputs.id }}"
        echo "The location is ${{ steps.step_one.outputs.location }}"
        echo "The provisioning state is ${{ steps.step_one.outputs.provisioning_state }}"
        
