on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: sn-cscharf/GitHubAction.JavaTest@v1.4
        with:
          who-to-greet: 'Mona the Octocat'
          subscriptionId: "some"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
