# The name of the work flow. Badges will use this name
name: '.NET code metrics'
on:
  push:
    branches: [ main ]
jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: .NET code metrics
      uses: sn-cscharf/GitHubAction.ResourceGroup@master
      with:
        region: westeurope
        tenant-id: ${{ secrets.TENANT }}
